include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for GMediaRender
LUCI_DEPENDS:=+gmediarender +luci-compat
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-gmediarender
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature