#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/vhusbd
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall vhusbd 2>/dev/null
}

status_service() {
    if pidof vhusbd > /dev/null 2>&1; then
        echo "running"
    else
        echo "stopped"
    fi
}
