#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/gmediarender

start_service() {
    config_load gmediarender

    config_get_bool enabled main enabled 0
    [ "$enabled" -eq 1 ] || return 0

    config_get      friendly_name main friendly_name "OpenWrt-Speaker"
    config_get      interface     main interface     "br-lan"
    config_get_bool enable_log    main enable_log    1
    config_get      logfile       main logfile       "/var/log/gmediarender.log"

    procd_open_instance

    if [ "$enable_log" -eq 1 ] && [ -n "$logfile" ]; then
        mkdir -p "$(dirname "$logfile")"
        procd_set_param command "$PROG" -f "$friendly_name" -I "$interface" "--logfile=$logfile"
    else
        procd_set_param command "$PROG" -f "$friendly_name" -I "$interface"
    fi

    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /etc/config/gmediarender
    procd_close_instance
}

stop_service() {
    :
}

reload_service() {
    stop
    start
}
