#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1


PROG=/usr/bin/gmediarender

start_service() {
    # 1. 加载 UCI 配置
    config_load gmediarender
    config_get_bool enabled main enabled 0
    

    [ "$enabled" -eq 1 ] || return 0

    config_get friendly_name main friendly_name "OpenWrt-Speaker"
    

    config_get interface main interface "br-lan"
    
    procd_open_instance
 
    procd_set_param command "$PROG" -f "$friendly_name" -I "$interface"
    
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /etc/config/gmediarender
    procd_close_instance
}

stop_service() {
    :
}

reload_service() {
    stop
    start
}
